package ui.common.resources

import androidx.compose.ui.graphics.Color

//Background
val TOP_BAR_BACKGROUND_COLOR = Color(0xFF181A1B)
val DIVIDER_COLOR = TOP_BAR_BACKGROUND_COLOR.copy(alpha = 0.3f)
val LEFT_MENU_BOTTOM_GRADIENT_COLOR = Color(0xFF3F4142)
val BACKGROUND_COLOR = Color(0xFF2F384B)

//Timer
val MAIN_SLIDER_COLOR = Color(0xFFFF5964)
val SHORT_BREAK_SLIDER_COLOR = Color(0xFF35A7FF)
val LONG_BREAK_SLIDER_COLOR = Color(0xFF6BF178)
val ROUNDS_SLIDER_COLOR = Color(0xFFFFFFFF)

//Text
val TEXT_COLOR = Color.White.copy(alpha = 0.8f)

//Button
val BUTTON_DEFAULT_BACKGROUND_COLOR = Color(0xFF577590) //0xFF00A6A6
val BUTTON_RED_BACKGROUND_COLOR = Color(0xFFE63B2E)
val BUTTON_GREEN_BACKGROUND_COLOR = Color(0xFF317B22)
val DISABLED_BUTTON_BACKGROUND_COMPOSITE_COLOR = Color.Black.copy(alpha = 0.5f)